version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      - run:
          name: "grant access to circle for dep locations"
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: "Install pipenv and deps"
          command: |
            sudo pip install pipenv
            pipenv install --ignore-pipfile --dev

      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      - run:
          name: "Test"
          command: pipenv run pytest
