version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/db?sslmode=disable
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: db

    steps:
      - checkout

      - run:
          name: "grant access to circle for dep locations"
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - restore_cache:
          key: v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: "Install pipenv and deps"
          command: |
            sudo pip install pipenv
            pipenv install --ignore-pipfile --dev

      - save_cache:
          key: v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "staticfiles"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          name: "Test"
          command: |
            pipenv run python manage.py collectstatic
            pipenv run pytest
